@baseURL= http://localhost:8001
#@baseURL = https://parked-car-driver-dev-api.onrender.com
###
GET {{baseURL}}


###
POST {{baseURL}}/register
Content-Type: application/json

{
    "name": "driver2",
    "email": "driver2",
    "phone": "1234567890",
    "password": "1234"
}

### 
# @name  login

POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "driver2",
    "password": "1234"
}
###

@access_token = {{login.response.body.token}}
@refresh_token = {{login.response.body.refreshToken}}

###
GET {{baseURL}}/protected 
Authorization: Bearer {{access_token}}


###
POST {{baseURL}}/search/quick
Content-Type: application/json

{
    "latitude": 37.3688,
    "longitude": -122.0279,
    "city": "sunnyvale"
}